website_title: ¯\_(ツ)_/¯
main_logo: logos/logo-dummy.png
main_logo_dark: logos/logo-dummy-dark.png
browser_title: 'Sit officia aliquip deserunt'
meta_description: 'Qui nisi consequat consequat tempor reprehenderit incididunt aute consectetur ipsum ut minim in ut.'
favicon_512x512: favicons/icon-512.png
favicon_96x96: favicons/icon-96.png
favicon_dark_512x512: favicons/icon-512-dark.png
favicon_dark_96x96: favicons/icon-96-dark.png
